<a href="https://colab.research.google.com/github/emdadjr/CSE413/blob/main/Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

np.random.seed(10)
mat1 = np.random.randint(1,50,size=(3,3))
print("Matrix with seed:\n",mat1)

Matrix with seed:
 [[10 37 16]
 [ 1 29 26]
 [30 49 30]]


In [11]:
mat2 =np.random.randint(1,50,size=(3,3))
print("Matrix without seed:\n", mat2)

Matrix without seed:
 [[12 25 44]
 [34  9 37]
 [15 14  6]]


**With fixed seed:**
  It generated a matrix that remains the same in each runs because of its function. It ensures the same same sequence of random numbers.

**Without fixed seed:**
  It ensures to generate random number or sequence each time of run.